# formula,file_tag,a,b,enabled
simplified,simplified,1.64,3.0,1
simplified,simplified,1.64,5.0,1
simplified,simplified,2.0,5.0,1
gaussian,gaussian,1.64,3.0,1
gaussian,gaussian,1.64,5.0,1
gaussian,gaussian,2.0,5.0,1
improved,improved,1.64,3.0,1
improved,improved,1.64,5.0,1
improved,improved,2.0,5.0,1
